global:                                                                         
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:                                                              
      monitor: 'exporter-metrics'                                                
                                                                                
alerting:
  alertmanagers:
    - static_configs:
      - targets: ["alertmanager:9093"]

scrape_configs:

- job_name: 'haproxy-exporter'
  static_configs:
  - targets: ['haproxy-exporter:9101']
    labels:
      alias: lb
- job_name: redis_exporter
  static_configs:
  - targets: ['redisexporter:9121']

- job_name: rabbitmq-exporter
  static_configs:
  - targets: ['rabbitmq-exporter:9090']

- job_name: mongodb-exporter
  static_configs:
  - targets: ['mongodb-exporter:9001']
  
- job_name: 'HostsMetrics'
  dns_sd_configs:
  - names:
    - node-exporter
    refresh_interval: 15s
    type: A
    port: 9100

- job_name: 'ContainerMetrics'
  static_configs:
    - targets:
      - 'rancher-server:9108'

- job_name: 'RancherServerMetrics'
  dns_sd_configs:
  - names:
    - cadvisor
    refresh_interval: 15s
    type: A
    port: 8080

- job_name: 'RancherApi'
  dns_sd_configs:
  - names:
    - 'prometheus-rancher-exporter'
    refresh_interval: 15s
    type: A
    port: 9173

- job_name: 'Prometheus'
  static_configs:
    - targets:
      - '127.0.0.1:9090'
